openapi: 3.0.3
info:
  title: Secure Disk Erasure - Central API
  version: 0.1.0
paths:
  /health:
    get:
      responses:
        '200': { description: OK }
  /v1/stations/register:
    post:
      requestBody: { required: true, content: { application/json: { schema: { type: object } } } }
      responses: { '200': { description: OK } }
  /v1/jobs:
    post:
      requestBody: { required: true, content: { application/json: { schema: { type: object } } } }
      responses: { '200': { description: OK } }
  /v1/results:
    post:
      requestBody: { required: true, content: { application/json: { schema: { type: object } } } }
      responses: { '200': { description: OK } }
